### ISSUE TITLE
DynamicPermission not working

### ISSUE THREAD

**Issue by juju1704** [EasyAbp/Abp.DynamicPermission#1]
Hi Easy fans, I got this error when using DynamicPermission. I have followed the steps but when I create the Model with auto-generated permissions and assigned permissions for the admin role Permissions don't seem to work. Other Permissions when running Migrator still work correctly. What should I do to fix this? 
![image](https://user-images.githubusercontent.com/101075772/178408117-f6ef1b8d-392b-4dca-8e4a-b4cb0df0ebff.png)

![image](https://user-images.githubusercontent.com/101075772/178408068-6f64b458-5384-4350-8e61-32ed7d4d3c68.png)

![image](https://user-images.githubusercontent.com/101075772/178408025-b0255bc6-67de-4087-82ed-85cd4b487f67.png)
![image](https://user-images.githubusercontent.com/101075772/178408164-e7a9b540-2b97-4aa0-a5c9-379ef9d9ca98.png)

**Comment by gdlcf88** [comment]
Sorry, I can't reproduce it. 

Try to run the tests and find problems:
https://github.com/EasyAbp/Abp.DynamicPermission/blob/main/test/EasyAbp.Abp.DynamicPermission.TestBase/DynamicPermissionDataSeedContributor.cs
https://github.com/EasyAbp/Abp.DynamicPermission/blob/main/test/EasyAbp.Abp.DynamicPermission.Application.Tests/Authorization/AuthorizationTests.cs

**Comment by juju1704** [comment]
> Sorry, I can't reproduce it.
> 
> Try to run the tests and find problems: https://github.com/EasyAbp/Abp.DynamicPermission/blob/main/test/EasyAbp.Abp.DynamicPermission.TestBase/DynamicPermissionDataSeedContributor.cs https://github.com/EasyAbp/Abp.DynamicPermission/blob/main/test/EasyAbp.Abp.DynamicPermission.Application.Tests/Authorization/AuthorizationTests.cs

I give up, your repo seems to be normal, but only after creating permission, my server can't recognize it.
